### ISSUE TITLE
KeyError: 'network_fn_d_state_dict'

### ISSUE THREAD

**Issue by AIBUWAN** [gaochen315/DynamicNeRF#9]
![2022-09-07 15-49-13 的屏幕截图](https://user-images.githubusercontent.com/107452659/188825815-9461eb62-ebe4-43ba-bc42-da691581d844.png)
Fixing random seed 1
factor  2
(270, 480, 3, 12)
(270, 480, 12)
(270, 480, 12)
(270, 480, 2, 12)
(270, 480, 12)
Loaded ./data/Balloon2/ 45.061882503348485 71.07477444180932
Loaded llff (12, 270, 480, 3) (60, 3, 5) [270.      480.      418.96216] ./data/Balloon2/
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['./logs/Balloon2_H270_DyNeRF_pretrain/300000.tar', './logs/Balloon2_H270_DyNeRF_pretrain/Pretrained_S.tar']
Reloading from ./logs/Balloon2_H270_DyNeRF_pretrain/Pretrained_S.tar
Traceback (most recent call last):
  File "run_nerf.py", line 768, in <module>
    train()
  File "run_nerf.py", line 215, in train
    render_kwargs_train, render_kwargs_test, start, grad_vars, optimizer = create_nerf(args)
  File "/home/chenghuan/DynamicNeRF/folder/run_nerf_helpers.py", line 355, in create_nerf
    model_d.load_state_dict(ckpt['network_fn_d_state_dict'])
KeyError: 'network_fn_d_state_dict'

Hi, thanks for your great work.

I wonder why there is no 'network_fn_d_state_dict' in ckpt.

Your model training time is slow . Can you take advantage of instant ngp-related work to increase speed?

我很疑惑为什么在我运行时ckpt中没有'network_fn_d_state_dict',您的模型训练时间很慢,我们能否利用 instant ngp 相关工作来提升您的模型的速度.期待您的回复.

**Comment by MasatoKawai** [comment]
If you just want to turn the code around, change ckpt_path in line 345 of run_nerf_helpers.py as follows

`ckpt_path = ckpts[-2]
`

Before the change, "Pretrained_S" is loaded, but if you want to load other models, you can specify them yourself.

**Comment by AIBUWAN** [comment]
@MasatoKawai I just want to load "Pretrained_S", but it dosen't work.
 
![2022-12-20 09-55-54 的屏幕截图](https://user-images.githubusercontent.com/107452659/208563584-2d83b5df-ac9f-4b1a-b3a1-84cc91084181.png)
